# Hardcoded training dataset
# Format: (text, category)

TRAINING_DATA = [
# ── MAKAN  ──────────────────────────────────────────────────
    ("beli kerupuk", "makan"),
    ("beli cilok", "makan"),
    ("beli siomay", "makan"),
    ("beli ketoprak", "makan"),
    ("beli gado gado", "makan"),
    ("beli lontong", "makan"),
    ("beli sate", "makan"),
    ("beli martabak", "makan"),
    ("beli bubur", "makan"),
    ("beli seblak", "makan"),
    ("beli batagor", "makan"),
    ("beli pempek", "makan"),
    ("beli dimsum", "makan"),
    ("beli pizza", "makan"),
    ("beli burger", "makan"),
    ("beli sandwich", "makan"),
    ("beli roti", "makan"),
    ("beli donat", "makan"),
    ("beli kue", "makan"),
    ("beli snack", "makan"),
    ("beli cemilan", "makan"),
    ("beli chiki", "makan"),
    ("beli biskuit", "makan"),
    ("beli coklat", "makan"),
    ("beli permen", "makan"),
    ("makan di warteg", "makan"),
    ("makan di kantin", "makan"),
    ("makan di rumah makan", "makan"),
    ("beli nasi kotak", "makan"),
    ("beli catering", "makan"),
    ("beli mie goreng", "makan"),
    ("beli kwetiau", "makan"),
    ("beli bihun", "makan"),
    ("beli nasi uduk", "makan"),
    ("beli nasi kuning", "makan"),
    ("beli pecel", "makan"),
    ("beli rawon", "makan"),
    ("beli opor", "makan"),
    ("beli rendang", "makan"),
    ("beli fried chicken", "makan"),
    ("beli kentang goreng", "makan"),

    # ── MINUM  ──────────────────────────────────────────────────
    ("beli es jeruk", "minum"),
    ("beli air mineral", "minum"),
    ("beli teh botol", "minum"),
    ("beli es campur", "minum"),
    ("beli wedang", "minum"),
    ("beli kopi sachet", "minum"),
    ("beli minuman kaleng", "minum"),
    ("beli air galon", "minum"),
    ("beli yakult", "minum"),
    ("beli pocari", "minum"),
    ("beli isotonic", "minum"),
    ("beli sprite", "minum"),
    ("beli coca cola", "minum"),
    ("beli fanta", "minum"),
    ("beli teh kotak", "minum"),
    ("beli jus alpukat", "minum"),
    ("beli jus mangga", "minum"),
    ("beli es dawet", "minum"),
    ("beli es doger", "minum"),
    ("beli es kelapa", "minum"),
    ("beli thai tea", "minum"),
    ("beli matcha", "minum"),
    ("beli americano", "minum"),
    ("beli latte", "minum"),
    ("beli es teh manis", "minum"),
    ("beli minuman energi", "minum"),
    ("beli extra joss", "minum"),

    # ── TRANSPORT  ──────────────────────────────────────────────
    ("isi bensin", "transport"),
    ("beli bbm", "transport"),
    ("servis motor", "transport"),
    ("servis mobil", "transport"),
    ("beli ban motor", "transport"),
    ("beli ban mobil", "transport"),
    ("bayar tol", "transport"),
    ("ganti oli", "transport"),
    ("beli spare part", "transport"),
    ("cuci motor", "transport"),
    ("cuci mobil", "transport"),
    ("naik taksi", "transport"),
    ("naik trans", "transport"),
    ("naik mrt", "transport"),
    ("naik lrt", "transport"),
    ("naik commuter", "transport"),
    ("naik krl", "transport"),
    ("beli tiket pesawat", "transport"),
    ("beli tiket kapal", "transport"),
    ("beli tiket travel", "transport"),
    ("sewa motor", "transport"),
    ("sewa mobil", "transport"),
    ("bayar parkir motor", "transport"),
    ("bayar parkir mobil", "transport"),
    ("beli helm", "transport"),
    ("beli jas hujan", "transport"),

    # ── HIBURAN  ────────────────────────────────────────────────
    ("karaoke", "hiburan"),
    ("beli voucher game", "hiburan"),
    ("bayar gym", "hiburan"),
    ("langganan youtube", "hiburan"),
    ("langganan disney", "hiburan"),
    ("langganan prime", "hiburan"),
    ("langganan vidio", "hiburan"),
    ("beli action figure", "hiburan"),
    ("beli merchandise", "hiburan"),
    ("nonton theater", "hiburan"),
    ("beli tiket pameran", "hiburan"),
    ("beli tiket pertunjukan", "hiburan"),
    ("main futsal", "hiburan"),
    ("main badminton", "hiburan"),
    ("main billiard", "hiburan"),
    ("beli tiket renang", "hiburan"),
    ("beli tiket zoo", "hiburan"),
    ("beli tiket museum", "hiburan"),
    ("beli puzzle", "hiburan"),
    ("beli board game", "hiburan"),
    ("beli kartu", "hiburan"),
    ("beli novel", "hiburan"),
    ("beli majalah", "hiburan"),
    ("download game", "hiburan"),
    ("top up game", "hiburan"),
    ("top up mobile legends", "hiburan"),
    ("top up ff", "hiburan"),

    # ── INCOME  ─────────────────────────────────────────────────
    ("jual barang", "income"),
    ("dapat refund", "income"),
    ("terima uang saku", "income"),
    ("dapat tip", "income"),
    ("dapat hadiah uang", "income"),
    ("dapat pinjaman", "income"),
    ("terima cicilan", "income"),
    ("dapat beasiswa", "income"),
    ("dapat bantuan", "income"),
    ("dapat thr", "income"),
    ("dapat intensif", "income"),
    ("dapat lembur", "income"),
    ("jual online", "income"),
    ("dapat hasil jualan", "income"),
    ("terima pembayaran", "income"),
    ("dapat dividen", "income"),
    ("dapat bunga", "income"),
    ("cairkan tabungan", "income"),
    ("dapat kiriman", "income"),
    ("dapat transferan", "income"),

    # ── TAGIHAN  ───────────────────────────────────────────
    ("bayar listrik", "tagihan"),
    ("bayar pdam", "tagihan"),
    ("bayar internet", "tagihan"),
    ("bayar wifi", "tagihan"),
    ("bayar indihome", "tagihan"),
    ("bayar telpon", "tagihan"),
    ("bayar pulsa", "tagihan"),
    ("beli pulsa", "tagihan"),
    ("beli paket data", "tagihan"),
    ("bayar cicilan", "tagihan"),
    ("bayar kos", "tagihan"),
    ("bayar kontrakan", "tagihan"),
    ("bayar sewa", "tagihan"),
    ("bayar asuransi", "tagihan"),
    ("bayar bpjs", "tagihan"),
    ("bayar iuran", "tagihan"),
    ("bayar pajak", "tagihan"),

    # ── BELANJA  ───────────────────────────────────────────
    ("beli baju", "belanja"),
    ("beli celana", "belanja"),
    ("beli sepatu", "belanja"),
    ("beli sandal", "belanja"),
    ("beli tas", "belanja"),
    ("beli dompet", "belanja"),
    ("beli jam tangan", "belanja"),
    ("beli aksesoris", "belanja"),
    ("beli kosmetik", "belanja"),
    ("beli skincare", "belanja"),
    ("beli parfum", "belanja"),
    ("beli sabun", "belanja"),
    ("beli shampo", "belanja"),
    ("beli deterjen", "belanja"),
    ("beli peralatan", "belanja"),
    ("beli alat tulis", "belanja"),
    ("beli charger", "belanja"),
    ("beli kabel", "belanja"),
    ("beli headset", "belanja"),
    ("beli elektronik", "belanja"),
    ("beli hp", "belanja"),
    ("beli laptop", "belanja"),
    ("belanja online", "belanja"),
    ("belanja shopee", "belanja"),
    ("belanja tokopedia", "belanja"),
]